# Azure build pipelines for Procdump-for-Linux
trigger:
  branches:
    include:
      - release/*
    exclude:
      - dev/*
      - test/*

pr:
  - master

resources:
  repositories:
    - repository: ProcDump
      type: github
      endpoint: sysinternals
      name: Microsoft/ProcDump-for-Linux
    - repository: obtemplates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main
extends:
  template: v2/OneBranch.NonOfficial.CrossPlat.yml@obtemplates
  parameters:
    globalSdl:
      tsa:
        enabled: false
      policheck:
        break: true
    stages:
      - stage: "Build_Run_Tests"
        jobs:
        - job: "ProcDump_Build_ARM64_Run_Tests"
          pool:
            type: linux
            hostArchitecture: arm64
          variables:
            LinuxContainerImage: 'mcr.microsoft.com/mirror/docker/library/ubuntu:22.04'
            ob_outputDirectory: '$(Build.SourcesDirectory)\out'
          steps:
          - script: |
              DEBIAN_FRONTEND=noninteractive apt -y update && apt install rsyslog -y
              rm -f /run/rsyslogd.pid
              service rsyslog start || true
            displayName: 'Enable syslog'

          - script: |
              DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" sudo
              chmod +x .devcontainer/install-ubuntu-dependencies.sh
              .devcontainer/install-ubuntu-dependencies.sh
            displayName: "Install pre-reqs for Ubuntu"

          - script: |
              clang --version
              clang++ --version
              gcc --version
            displayName: 'List compiler versions'

          - template: templates/build.yaml@ProcDump

          - script: |
              cd procdump_build/tests/integration
              ./run.sh
            displayName: 'Run unit tests'

        - job: "ProcDump_Build_AMD64_Run_Tests"
          pool:
            type: linux
          variables:
            LinuxContainerImage: 'mcr.microsoft.com/mirror/docker/library/ubuntu:22.04'
            ob_outputDirectory: '$(Build.SourcesDirectory)\out'
          steps:
          - script: |
              DEBIAN_FRONTEND=noninteractive apt -y update && apt install rsyslog -y
              rm -f /run/rsyslogd.pid
              service rsyslog start || true
            displayName: 'Enable syslog'

          - script: |
              DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" sudo
              chmod +x .devcontainer/install-ubuntu-dependencies.sh
              .devcontainer/install-ubuntu-dependencies.sh
            displayName: "Install pre-reqs for Ubuntu"

          - script: |
              clang --version
              clang++ --version
              gcc --version
            displayName: 'List compiler versions'

          - template: templates/build.yaml@ProcDump

          - script: |
              apt install -y iproute2
              echo "Check port 5032" && ss -tulnp | grep 5032
              cd procdump_build/tests/integration
              ./run.sh
            displayName: 'Run unit tests'

        - job: "ProcDump_Build_MACOS_Run_Tests"
          pool:
            type: linux
            isCustom: true
            name: Azure Pipelines
            vmImage: 'macOS-latest'
          variables:
            ob_outputDirectory: '$(Build.SourcesDirectory)/out'
          steps:

          - script: |
              sw_vers
            displayName: 'Diagnostics'

          - template: templates/build.yaml@ProcDump

          - script: |
              cd procdump_build/tests/integration
              sudo ./run.sh
            displayName: 'Run unit tests'
